export enum RequestTypeCategory {
    Alarm = 'ala',
    AnimalRelated = 'ani',
    AssistHouseless = 'ash',
    ChildInDanger = 'chd',
    CommunityCare = 'coc',
    Copwatch = 'cpw',
    DeescalationMediation = 'dem',
    Disturbance = 'dis',
    DomesticIntimatePartnerViolence = 'dov',
    EmotionalSupport = 'emo',
    Error = 'err',
    FirstAid = 'fai',
    Harassment = 'har',
    Internal = 'int',
    InterpersonalHarm = 'inh',
    Kidnapping = 'kid',
    LegalSupport = 'les',
    MentalHealthCrisis = 'mhc',
    MissingFoundPerson = 'mfp',
    ObstructingTrafficWalkway = 'otw',
    SexualViolence = 'sev',
    Shooting = 'sho',
    SubstanceUse = 'suu',
    TheftFraud = 'thf',
    VerbalResourceAssistance = 'vra',
    WitnessingTrouble = 'wit',
}

export enum RequestType {
    CarAlarmGoingOff = RequestTypeCategory.Alarm + ':' + 'a1',
    HomeBusinessAlarmGoingOff = RequestTypeCategory.Alarm + Delimiters.Enum + 'a2',
    AnimalCruelty = RequestTypeCategory.AnimalRelated + Delimiters.Enum + 'an1',
    LooseAnimalDangerousUnknown	= RequestTypeCategory.AnimalRelated	+ Delimiters.Enum + 'an2',
    LooseAnimalFriendly = RequestTypeCategory.AnimalRelated	+ Delimiters.Enum + 'an3',
    LostPetAnimal = RequestTypeCategory.AnimalRelated + Delimiters.Enum + 'an4',
    OtherAssistanceWithAnimal = RequestTypeCategory.AnimalRelated + Delimiters.Enum + 'an5',
    TrappedPetAnimal = RequestTypeCategory.AnimalRelated + Delimiters.Enum + 'an6',
    WildlifeViolations = RequestTypeCategory.AnimalRelated + Delimiters.Enum + 'an7',
    PersonWhoIsHouselessNeedsAssistance = RequestTypeCategory.AssistHouseless + Delimiters.Enum + 'ah1',
    SleepingInPublicPlace = RequestTypeCategory.AssistHouseless + Delimiters.Enum + 'ah2',
    VigilanteHarassingPeopleWhoAreHouseless = RequestTypeCategory.AssistHouseless + Delimiters.Enum + 'ah3',
    ChildAbandoned = RequestTypeCategory.ChildInDanger + Delimiters.Enum + 'minor1',
    ChildAbuseByParentGuardian = RequestTypeCategory.ChildInDanger + Delimiters.Enum + 'minor2',
    ChildAbuseEndangeredGeneral = RequestTypeCategory.ChildInDanger + Delimiters.Enum + 'minor3',
    ChildMolested = RequestTypeCategory.ChildInDanger + Delimiters.Enum + 'minor4',
    ChildNeglect = RequestTypeCategory.ChildInDanger + Delimiters.Enum + 'minor5',
    RunawayChild = RequestTypeCategory.ChildInDanger + Delimiters.Enum + 'minor6',
    AbandonedVehicle = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc1',
    CallerInDanger = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc2',
    CheckBuildingForSafety = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc3',
    DetermineIfHelpIsNeededForPerson = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc4',
    EmployeeCoworkerHasBeenAbsent = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc5',
    InoperableVehicle = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc6',
    LitteringDumpingTrash = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc7',
    LockedOutOfResidenceAccident = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc8',
    Loitering = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc9',
    NeedHelpUndefined = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc10',
    PersonCallerTrappedSomewhere = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc11',
    SexWorkerNeedsHelp = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc12',
    SuspiciousPerson = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc13',
    SuspiciousSituation = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc14',
    SuspiciousVehicle = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc15',
    UnknownProblem = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc16',
    WelfareCheckGeneralUnknown = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc17',
    YouthOutsideLateAtNightPastCurfew = RequestTypeCategory.CommunityCare + Delimiters.Enum + 'cc18',
    ArrestingAMinor = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw1',
    CallerBeingArrested = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw2',
    CopsOnTheTrain = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw3',
    EncampmentRaid = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw4',
    HaveFootageEvidenceOfPoliceHarm = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw5',
    PoliceCheckpoint = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw6',
    PoliceGivingTickets = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw7',
    PoliceSearchAndFrisk = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw8',
    PoliceTakingDestroyingProperty = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw9',
    PoliceTamperingWithEvidence = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw10',
    PoliceAgencyHarassmentOfPeopleWhoAreHouseless = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw11',
    VerbalAbuseHarrassmentByPoliceOfficer = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw12',
    ViolenceHarmByPoliceOfficer = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw13',
    WitnessingAnArrest = RequestTypeCategory.Copwatch + Delimiters.Enum + 'cw14',
    ArgumentAmongFamily = RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm1',
    ArgumentBetweenAdults	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm2',
    ArgumentBetweenYouth = RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm3',
    ArgumentBetweenYouthAndAdults	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm4',
    DirectActionAssistance	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm5',
    FalseImprisonmentByBusiness	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm6',
    Fight = RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm7',
    FraudAtPlaceOfBusiness	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm8',
    LockedOutOfResidenceByCoHabitant	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm9',
    MarchParadeAssistance = RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm10',
    NoMoneyNotPayingBusinessAfterService	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm11',
    RequestToStandbyAndPreservePeace	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm12',
    Shoplifting	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm13',
    Trespassing	= RequestTypeCategory.DeescalationMediation + Delimiters.Enum + 'dm14',
    Fireworks = RequestTypeCategory.Disturbance + Delimiters.Enum + 'dist1',
    GeneralDisturbance = RequestTypeCategory.Disturbance + Delimiters.Enum + 'dist2',
    NoiseComplaint = RequestTypeCategory.Disturbance + Delimiters.Enum + 'dist3',
    ReportingADemonstrationProtest = RequestTypeCategory.Disturbance + Delimiters.Enum + 'dist4',
    SexualActivityConsensualInPublic = RequestTypeCategory.Disturbance + Delimiters.Enum + 'dist5',
    IntimatePartnerViolenceNoInjury = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv1',
    IntimatePartnerViolenceWithInjury = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv2',
    MoveOutWhileAbusivePartnerIsGone = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv3',
    OtherRoommateIssue = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv4',
    PhysicalViolenceBetweenCoHabitants = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv5',
    RestrainingOrderViolationPartnerSpouse = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv6',
    SexualAssaultRapeByPartner = RequestTypeCategory.DomesticIntimatePartnerViolence + Delimiters.Enum + 'ipv7',
    Advice = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es1',
    PostpartumDepression = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es2',
    ProcessingChildhoodAbuse = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es3',
    ProcessingHomophobicParentsRejection = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es4',
    ProcessingIPVDomesticViolence = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es5',
    ProcessingLossOfALovedOne = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es6',
    ProcessingOtherUnlistedTrauma = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es7',
    ProcessingPregnancyAbortion = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es8',
    ProcessingSexualViolence = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es9',
    ProcessingStateViolence = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es10',
    StressAnxiety = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es11',
    SuicidalIdeationSuicidePrevention = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es12',
    WitnessDeathMurder = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es13',
    WitnessSuicideCompleted = RequestTypeCategory.EmotionalSupport + Delimiters.Enum + 'es14',
    AccidentalCallCrywolf = RequestTypeCategory.Error + Delimiters.Enum + 'err1',
    CallerHungUp = RequestTypeCategory.Error + Delimiters.Enum + 'err2',
    CantUnderstandCaller = RequestTypeCategory.Error + Delimiters.Enum + 'err3',
    PrankCall = RequestTypeCategory.Error + Delimiters.Enum + 'err4',
    RequestForHelpWhenClosed = RequestTypeCategory.Error + Delimiters.Enum + 'err5',
    RudePrejudicedCaller = RequestTypeCategory.Error + Delimiters.Enum + 'err6',
    TestCallTraining = RequestTypeCategory.Error + Delimiters.Enum + 'err7',
    BiteOrSting = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa1',
    BleedingInternal = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa2',
    BleedingOtherWoundPuncture = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa3',
    BluntTraumaContusion = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa4',
    BrokenBone = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa5',
    BulletWound = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa6',
    BurnHeatChemicalElectricalEtc = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa7',
    ChestPainHeartAttackStroke = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa8',
    Choking = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa9',
    ComplaintOfPainGeneral = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa10',
    Dehydrated = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa11',
    Diabetic = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa12',
    DigestiveIssueDiarrheaFoodPoisoning = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa13',
    OtherMajorInjury = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa14',
    OtherMinorInjury = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa15',
    Overdose = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa16',
    PersonDownUnconscious = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa17',
    Poison = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa18',
    PregnancyDeliveryOfBaby = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa19',
    RespiratoryBreathingIssue = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa20',
    Seizure = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa21',
    SickCovid = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa22',
    SickNotCovidUnknown = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa23',
    StabWound = RequestTypeCategory.FirstAid + Delimiters.Enum + 'fa24',
    HarassmentGeneral = RequestTypeCategory.Harassment + Delimiters.Enum + 'h1',
    Peeper = RequestTypeCategory.Harassment + Delimiters.Enum + 'h2',
    Stalker = RequestTypeCategory.Harassment + Delimiters.Enum + 'h3',
    AssistResponder = RequestTypeCategory.Internal + Delimiters.Enum + 'int1',
    ResponderInjured = RequestTypeCategory.Internal + Delimiters.Enum + 'int2',
    HateCrimeSlur = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih1',
    InterpersonalViolenceGeneral = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih2',
    MaliciousDamageToPersonalProperty = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih3',
    PhysicalViolenceNoInjury = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih4',
    PhysicalViolenceWInjury = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih5',
    RestrainingOrderViolationOther = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih6',
    ThreatenNoWeapon = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih7',
    ThreatenWWeaponOrSubstance = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih8',
    VerbalEmotionalFinancialAbuse = RequestTypeCategory.InterpersonalHarm + Delimiters.Enum + 'ih9',
    AbductionByFamilyMember = RequestTypeCategory.Kidnapping + Delimiters.Enum + 'kn1',
    CoHabitantPreventingPersonFromLeaving = RequestTypeCategory.Kidnapping + Delimiters.Enum + 'kn2',
    KidnappingGeneralUnknown = RequestTypeCategory.Kidnapping + Delimiters.Enum + 'kn3',
    ChildProtectiveServicesDispute = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls1',
    EvictionLandlordTenantIssue = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls2',
    GenderAffirmingLegalSupport = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls3',
    ImmigrationDeportationSupport = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls4',
    LandlordTenantDisputeGeneral = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls5',
    LandlordTenantDisputeLockoutEviction = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls6',
    LegalSupportAtProtestDirectAction = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls7',
    MassArrest = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls8',
    OtherUnlistedLegalSupport = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls9',
    SharedCustodyIssuesWithChildren = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls10',
    SupportFilingComplaintAgainstPoliceOfficer = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls11',
    WorkplaceLegalSupport = RequestTypeCategory.LegalSupport + Delimiters.Enum + 'ls12',
    MentalHealthCrisisGeneralNonViolent = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc1',
    MentalIllnessAutism = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc2',
    MentalIllnessBipolar = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc3',
    MentalIllnessDementiaDisorientation = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc4',
    MentalIllnessDepressionAnxiety = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc5',
    MentalIllnessEatingDisorder = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc6',
    MentalIllnessNonviolentUndefinedPsychosis = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc7',
    MentalIllnessPTSD = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc8',
    MentalIllnessSchizophrenia = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc9',
    MentalIllnessViolentUndefinedPsychosis = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc10',
    PublicNudityIndecentExposure = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc11',
    SelfHarming = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc12',
    SuicideAttemptThreat = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc13',
    UrinatingDefecatingInPublic = RequestTypeCategory.MentalHealthCrisis + Delimiters.Enum + 'mhc14',
    FoundAdult = RequestTypeCategory.MissingFoundPerson + Delimiters.Enum + 'miss1',
    FoundYouth = RequestTypeCategory.MissingFoundPerson + Delimiters.Enum + 'miss2',
    MissingPersonIsAtRisk = RequestTypeCategory.MissingFoundPerson + Delimiters.Enum + 'miss3',
    YouthDidNotArriveAtHomeSchool = RequestTypeCategory.MissingFoundPerson + Delimiters.Enum + 'miss4',
    ObjectObstructingTraffic = RequestTypeCategory.ObstructingTrafficWalkway + Delimiters.Enum + 'traff1',
    PersonObstructingTraffic = RequestTypeCategory.ObstructingTrafficWalkway + Delimiters.Enum + 'traff2',
    TreeDown = RequestTypeCategory.ObstructingTrafficWalkway + Delimiters.Enum + 'traff3',
    VehicleBlockingDriveway = RequestTypeCategory.ObstructingTrafficWalkway + Delimiters.Enum + 'traff4',
    VehicleDoubleParking = RequestTypeCategory.ObstructingTrafficWalkway + Delimiters.Enum + 'traff5',
    AttemptedRape = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv1',
    AttemptedSexualAssault = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv2',
    Incest = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv3',
    Rape = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv4',
    RevengePorn = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv5',
    SexualAssault = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv6',
    SexualAssaultRapeNotByIntimatePartner = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv7',
    SexualHarassment = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv8',
    SexualHarmByPoliceOfficer = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv9',
    StatutoryRapeSexBetweenMinorAndAdult = RequestTypeCategory.SexualViolence + Delimiters.Enum + 'sv10',
    HeardShooting = RequestTypeCategory.Shooting + Delimiters.Enum + 'sh1',
    SawShootingInCommunity = RequestTypeCategory.Shooting + Delimiters.Enum + 'sh2',
    ShootingAtCallerDirectHomeCar = RequestTypeCategory.Shooting + Delimiters.Enum + 'sh3',
    ShootingAtNeighborDirectHomeCar = RequestTypeCategory.Shooting + Delimiters.Enum + 'sh4',
    IntoxicatedInBarClub = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub1',
    IntoxicatedInVehicleNotDriving = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub2',
    IntoxicatedInsideBuilding = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub3',
    IntoxicatedOnTheStreetSidewalk = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub4',
    NeedlesDrugParaphernaliaOnGround = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub5',
    SubstanceUseInPublic = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub6',
    YouthChildWithControlledSubstance = RequestTypeCategory.SubstanceUse + Delimiters.Enum + 'sub7',
    AttemptedBurglaryRobbery = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf1',
    Carjacking = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf2',
    FraudGeneral = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf3',
    HomeOfficeBurglarized = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf4',
    Robbery = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf5',
    StolenVehicle = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf6',
    TheftOfPersonalProperty = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf7',
    VehicleBurglarized = RequestTypeCategory.TheftFraud + Delimiters.Enum + 'tf8',
    AccessingAnAbortion = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst1',
    CallerRecievingPrankCalls = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst2',
    ChronicCaller = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst3',
    FindingCovidTesting = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst4',
    FindingShelter = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst5',
    FindingSTDSTITesting = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst6',
    GeneralComplaints = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst7',
    HelpGettingFoodWater = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst8',
    HelpGettingMedicine = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst9',
    InfoAboutCommunityMeeting = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst10',
    InfoAboutThisProgramCrisisTeam = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst11',
    NeedATow = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst12',
    OtherFinancialMutualAid = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst13',
    Transport = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst14',
    UtilitiesShutOff = RequestTypeCategory.VerbalResourceAssistance	+ Delimiters.Enum + 'asst15',
    BrandishingWeapon = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt1',
    Gambling = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt2',
    NegativeActivityWhereChildrenArePresent = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt3',
    PersonWithAGun = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt4',
    SellingDrugs = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt5',
    SexTrafficking = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt6',
    SexWork = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt7',
    ThrowingObjectsSubstance = RequestTypeCategory.WitnessingTrouble + Delimiters.Enum + 'wt8',
}

export const RequestTypeCategoryToLabelMap: { [key in RequestTypeCategory]: string } = {
    [RequestTypeCategory.Alarm]: 'Alarm',
    [RequestTypeCategory.AnimalRelated]: 'Animal-Related',
    [RequestTypeCategory.AssistHouseless]: 'Assist Houseless',
    [RequestTypeCategory.ChildInDanger]: 'Child in Danger',
    [RequestTypeCategory.CommunityCare]: 'Community Care',
    [RequestTypeCategory.Copwatch]: 'Copwatch',
    [RequestTypeCategory.DeescalationMediation]: 'De-escalation/Mediation',
    [RequestTypeCategory.Disturbance]: 'Disturbance',
    [RequestTypeCategory.DomesticIntimatePartnerViolence]: 'Domestic/Intimate Partner Violence',
    [RequestTypeCategory.EmotionalSupport]: 'Emotional Support',
    [RequestTypeCategory.Error]: 'Error',
    [RequestTypeCategory.FirstAid]: 'First Aid',
    [RequestTypeCategory.Harassment]: 'Harassment',
    [RequestTypeCategory.Internal]: 'Internal',
    [RequestTypeCategory.InterpersonalHarm]: 'Interpersonal Harm',
    [RequestTypeCategory.Kidnapping]: 'Kidnapping',
    [RequestTypeCategory.LegalSupport]: 'Legal Support',
    [RequestTypeCategory.MentalHealthCrisis]: 'Mental Health Crisis',
    [RequestTypeCategory.MissingFoundPerson]: 'Missing/Found Person',
    [RequestTypeCategory.ObstructingTrafficWalkway]: 'Obstructing Traffic/Walkway',
    [RequestTypeCategory.SexualViolence]: 'Sexual Violence',
    [RequestTypeCategory.Shooting]: 'Shooting',
    [RequestTypeCategory.SubstanceUse]: 'Substance Use',
    [RequestTypeCategory.TheftFraud]: 'Theft/Fraud',
    [RequestTypeCategory.VerbalResourceAssistance]: 'Verbal/Resource Assistance',
    [RequestTypeCategory.WitnessingTrouble]: 'Witnessing Trouble',
}

export const RequestTypeToLabelMap: { [key in RequestType]: string } = {
    [RequestType.CarAlarmGoingOff]: `Car alarm going off`,
    [RequestType.HomeBusinessAlarmGoingOff]: `Home/Business alarm going off`,
    [RequestType.AnimalCruelty]: `Animal Cruelty`,
    [RequestType.LooseAnimalDangerousUnknown]: `Loose animal -- dangerous/unknown`,
    [RequestType.LooseAnimalFriendly]: `Loose animal -- friendly`,
    [RequestType.LostPetAnimal]: `Lost pet/animal`,
    [RequestType.OtherAssistanceWithAnimal]: `Other assistance with animal`,
    [RequestType.TrappedPetAnimal]: `Trapped pet/animal`,
    [RequestType.WildlifeViolations]: `Wildlife violations`,
    [RequestType.PersonWhoIsHouselessNeedsAssistance]: `Person who is houseless needs assistance`,
    [RequestType.SleepingInPublicPlace]: `Sleeping in public place`,
    [RequestType.VigilanteHarassingPeopleWhoAreHouseless]: `Vigilante harassing people who are houseless`,
    [RequestType.ChildAbandoned]: `Child Abandoned`,
    [RequestType.ChildAbuseByParentGuardian]: `Child Abuse (by parent/guardian)`,
    [RequestType.ChildAbuseEndangeredGeneral]: `Child Abuse/Endangered (general)`,
    [RequestType.ChildMolested]: `Child Molested`,
    [RequestType.ChildNeglect]: `Child Neglect`,
    [RequestType.RunawayChild]: `Runaway child`,
    [RequestType.AbandonedVehicle]: `Abandoned Vehicle`,
    [RequestType.CallerInDanger]: `Caller in Danger`,
    [RequestType.CheckBuildingForSafety]: `Check building for safety`,
    [RequestType.DetermineIfHelpIsNeededForPerson]: `Determine if help is needed for person`,
    [RequestType.EmployeeCoworkerHasBeenAbsent]: `Employee/coworker has been absent`,
    [RequestType.InoperableVehicle]: `Inoperable Vehicle`,
    [RequestType.LitteringDumpingTrash]: `Littering/Dumping trash`,
    [RequestType.LockedOutOfResidenceAccident]: `Locked out of residence - accident`,
    [RequestType.Loitering]: `Loitering`,
    [RequestType.NeedHelpUndefined]: `Need Help (Undefined)`,
    [RequestType.PersonCallerTrappedSomewhere]: `Person/caller trapped somewhere`,
    [RequestType.SexWorkerNeedsHelp]: `Sex worker needs help`,
    [RequestType.SuspiciousPerson]: `Suspicious person`,
    [RequestType.SuspiciousSituation]: `Suspicious situation`,
    [RequestType.SuspiciousVehicle]: `Suspicious vehicle`,
    [RequestType.UnknownProblem]: `Unknown Problem`,
    [RequestType.WelfareCheckGeneralUnknown]: `Welfare check (general/unknown)`,
    [RequestType.YouthOutsideLateAtNightPastCurfew]: `Youth outside late at night/past curfew`,
    [RequestType.ArrestingAMinor]: `Arresting a minor`,
    [RequestType.CallerBeingArrested]: `Caller being arrested`,
    [RequestType.CopsOnTheTrain]: `Cops on the train`,
    [RequestType.EncampmentRaid]: `Encampment Raid`,
    [RequestType.HaveFootageEvidenceOfPoliceHarm]: `Have footage/evidence of police harm`,
    [RequestType.PoliceCheckpoint]: `Police checkpoint`,
    [RequestType.PoliceGivingTickets]: `Police giving tickets`,
    [RequestType.PoliceSearchAndFrisk]: `Police search & frisk`,
    [RequestType.PoliceTakingDestroyingProperty]: `Police taking/destroying property`,
    [RequestType.PoliceTamperingWithEvidence]: `Police tampering with evidence`,
    [RequestType.PoliceAgencyHarassmentOfPeopleWhoAreHouseless]: `Police/agency harassment of people who are houseless`,
    [RequestType.VerbalAbuseHarrassmentByPoliceOfficer]: `Verbal abuse/harrassment by police officer`,
    [RequestType.ViolenceHarmByPoliceOfficer]: `Violence/harm by police officer`,
    [RequestType.WitnessingAnArrest]: `Witnessing an arrest`,
    [RequestType.ArgumentAmongFamily]: `Argument among family`,
    [RequestType.ArgumentBetweenAdults]: `Argument between adults`,
    [RequestType.ArgumentBetweenYouth]: `Argument between youth`,
    [RequestType.ArgumentBetweenYouthAndAdults]: `Argument between youth & adults`,
    [RequestType.DirectActionAssistance]: `Direct Action assistance`,
    [RequestType.FalseImprisonmentByBusiness]: `False imprisonment by business`,
    [RequestType.Fight]: `Fight`,
    [RequestType.FraudAtPlaceOfBusiness]: `Fraud at place of business`,
    [RequestType.LockedOutOfResidenceByCoHabitant]: `Locked out of residence by co-habitant`,
    [RequestType.MarchParadeAssistance]: `March/parade assistance`,
    [RequestType.NoMoneyNotPayingBusinessAfterService]: `No money/not paying business after service`,
    [RequestType.RequestToStandbyAndPreservePeace]: `Request to standby and preserve peace`,
    [RequestType.Shoplifting]: `Shoplifting`,
    [RequestType.Trespassing]: `Trespassing`,
    [RequestType.Fireworks]: `Fireworks`,
    [RequestType.GeneralDisturbance]: `General disturbance`,
    [RequestType.NoiseComplaint]: `Noise complaint`,
    [RequestType.ReportingADemonstrationProtest]: `Reporting a demonstration/protest`,
    [RequestType.SexualActivityConsensualInPublic]: `Sexual Activity (consensual) in Public`,
    [RequestType.IntimatePartnerViolenceNoInjury]: `Intimate Partner Violence - no injury`,
    [RequestType.IntimatePartnerViolenceWithInjury]: `Intimate Partner Violence - with injury`,
    [RequestType.MoveOutWhileAbusivePartnerIsGone]: `Move out while abusive partner is gone`,
    [RequestType.OtherRoommateIssue]: `Other roommate issue`,
    [RequestType.PhysicalViolenceBetweenCoHabitants]: `Physical violence (between co-habitants)`,
    [RequestType.RestrainingOrderViolationPartnerSpouse]: `Restraining Order Violation - partner/spouse`,
    [RequestType.SexualAssaultRapeByPartner]: `Sexual assault/rape (by partner)`,
    [RequestType.Advice]: `Advice`,
    [RequestType.PostpartumDepression]: `Postpartum depression`,
    [RequestType.ProcessingChildhoodAbuse]: `Processing childhood abuse`,
    [RequestType.ProcessingHomophobicParentsRejection]: `Processing homophobic parents/rejection`,
    [RequestType.ProcessingIPVDomesticViolence]: `Processing IPV/domestic violence`,
    [RequestType.ProcessingLossOfALovedOne]: `Processing loss of a loved one`,
    [RequestType.ProcessingOtherUnlistedTrauma]: `Processing other/unlisted trauma`,
    [RequestType.ProcessingPregnancyAbortion]: `Processing pregnancy/abortion`,
    [RequestType.ProcessingSexualViolence]: `Processing sexual violence`,
    [RequestType.ProcessingStateViolence]: `Processing state violence`,
    [RequestType.StressAnxiety]: `Stress/anxiety`,
    [RequestType.SuicidalIdeationSuicidePrevention]: `Suicidal Ideation/Suicide Prevention`,
    [RequestType.WitnessDeathMurder]: `Witness death/murder`,
    [RequestType.WitnessSuicideCompleted]: `Witness suicide completed`,
    [RequestType.AccidentalCallCrywolf]: `Accidental call/crywolf`,
    [RequestType.CallerHungUp]: `Caller hung up`,
    [RequestType.CantUnderstandCaller]: `Can't Understand Caller`,
    [RequestType.PrankCall]: `Prank Call`,
    [RequestType.RequestForHelpWhenClosed]: `Request for help when closed`,
    [RequestType.RudePrejudicedCaller]: `Rude/Prejudiced caller`,
    [RequestType.TestCallTraining]: `Test Call/Training`,
    [RequestType.BiteOrSting]: `Bite or sting`,
    [RequestType.BleedingInternal]: `Bleeding (internal)`,
    [RequestType.BleedingOtherWoundPuncture]: `Bleeding (other wound/puncture)`,
    [RequestType.BluntTraumaContusion]: `Blunt trauma/contusion`,
    [RequestType.BrokenBone]: `Broken bone`,
    [RequestType.BulletWound]: `Bullet wound`,
    [RequestType.BurnHeatChemicalElectricalEtc]: `Burn (heat/chemical/electrical/etc)`,
    [RequestType.ChestPainHeartAttackStroke]: `Chest pain/heart attack/stroke`,
    [RequestType.Choking]: `Choking`,
    [RequestType.ComplaintOfPainGeneral]: `Complaint of pain (general)`,
    [RequestType.Dehydrated]: `Dehydrated`,
    [RequestType.Diabetic]: `Diabetic`,
    [RequestType.DigestiveIssueDiarrheaFoodPoisoning]: `Digestive Issue (Diarrhea, Food Poisoning)`,
    [RequestType.OtherMajorInjury]: `Other Major Injury`,
    [RequestType.OtherMinorInjury]: `Other Minor Injury`,
    [RequestType.Overdose]: `Overdose`,
    [RequestType.PersonDownUnconscious]: `Person down/unconscious`,
    [RequestType.Poison]: `Poison`,
    [RequestType.PregnancyDeliveryOfBaby]: `Pregnancy/delivery of baby`,
    [RequestType.RespiratoryBreathingIssue]: `Respiratory/Breathing Issue`,
    [RequestType.Seizure]: `Seizure`,
    [RequestType.SickCovid]: `Sick (Covid)`,
    [RequestType.SickNotCovidUnknown]: `Sick (not Covid/unknown)`,
    [RequestType.StabWound]: `Stab wound`,
    [RequestType.HarassmentGeneral]: `Harassment (general)`,
    [RequestType.Peeper]: `Peeper`,
    [RequestType.Stalker]: `Stalker`,
    [RequestType.AssistResponder]: `Assist Responder`,
    [RequestType.ResponderInjured]: `Responder Injured`,
    [RequestType.HateCrimeSlur]: `Hate Crime/Slur`,
    [RequestType.InterpersonalViolenceGeneral]: `Interpersonal Violence (general)`,
    [RequestType.MaliciousDamageToPersonalProperty]: `Malicious damage to personal property`,
    [RequestType.PhysicalViolenceNoInjury]: `Physical violence (no injury)`,
    [RequestType.PhysicalViolenceWInjury]: `Physical violence (w/injury)`,
    [RequestType.RestrainingOrderViolationOther]: `Restraining Order Violation - other`,
    [RequestType.ThreatenNoWeapon]: `Threaten (no weapon)`,
    [RequestType.ThreatenWWeaponOrSubstance]: `Threaten (w/weapon or substance)`,
    [RequestType.VerbalEmotionalFinancialAbuse]: `Verbal/Emotional/Financial Abuse`,
    [RequestType.AbductionByFamilyMember]: `Abduction by family member`,
    [RequestType.CoHabitantPreventingPersonFromLeaving]: `Co-habitant preventing person from leaving`,
    [RequestType.KidnappingGeneralUnknown]: `Kidnapping (general/unknown)`,
    [RequestType.ChildProtectiveServicesDispute]: `Child Protective Services dispute`,
    [RequestType.EvictionLandlordTenantIssue]: `Eviction/landlord-tenant issue`,
    [RequestType.GenderAffirmingLegalSupport]: `Gender-affirming legal support`,
    [RequestType.ImmigrationDeportationSupport]: `Immigration/Deportation support`,
    [RequestType.LandlordTenantDisputeGeneral]: `Landlord-Tenant Dispute - general`,
    [RequestType.LandlordTenantDisputeLockoutEviction]: `Landlord-Tenant Dispute - Lockout/Eviction`,
    [RequestType.LegalSupportAtProtestDirectAction]: `Legal support at protest/direct action`,
    [RequestType.MassArrest]: `Mass arrest`,
    [RequestType.OtherUnlistedLegalSupport]: `Other/unlisted legal support`,
    [RequestType.SharedCustodyIssuesWithChildren]: `Shared Custody Issues with children`,
    [RequestType.SupportFilingComplaintAgainstPoliceOfficer]: `Support filing complaint against police officer`,
    [RequestType.WorkplaceLegalSupport]: `Workplace legal support`,
    [RequestType.MentalHealthCrisisGeneralNonViolent]: `Mental Health Crisis (general/non-violent)`,
    [RequestType.MentalIllnessAutism]: `Mental Illness - Autism`,
    [RequestType.MentalIllnessBipolar]: `Mental Illness - Bipolar`,
    [RequestType.MentalIllnessDementiaDisorientation]: `Mental Illness - Dementia/Disorientation`,
    [RequestType.MentalIllnessDepressionAnxiety]: `Mental Illness - Depression/Anxiety`,
    [RequestType.MentalIllnessEatingDisorder]: `Mental Illness - Eating Disorder`,
    [RequestType.MentalIllnessNonviolentUndefinedPsychosis]: `Mental Illness - Nonviolent Undefined Psychosis`,
    [RequestType.MentalIllnessPTSD]: `Mental Illness - PTSD`,
    [RequestType.MentalIllnessSchizophrenia]: `Mental Illness - Schizophrenia`,
    [RequestType.MentalIllnessViolentUndefinedPsychosis]: `Mental Illness - Violent Undefined Psychosis`,
    [RequestType.PublicNudityIndecentExposure]: `Public nudity/indecent exposure`,
    [RequestType.SelfHarming]: `Self-harming`,
    [RequestType.SuicideAttemptThreat]: `Suicide Attempt/Threat`,
    [RequestType.UrinatingDefecatingInPublic]: `Urinating/defecating in public`,
    [RequestType.FoundAdult]: `Found Adult`,
    [RequestType.FoundYouth]: `Found Youth`,
    [RequestType.MissingPersonIsAtRisk]: `Missing Person is at risk`,
    [RequestType.YouthDidNotArriveAtHomeSchool]: `Youth did not arrive at home/school`,
    [RequestType.ObjectObstructingTraffic]: `Object obstructing traffic`,
    [RequestType.PersonObstructingTraffic]: `Person Obstructing Traffic`,
    [RequestType.TreeDown]: `Tree Down`,
    [RequestType.VehicleBlockingDriveway]: `Vehicle Blocking Driveway`,
    [RequestType.VehicleDoubleParking]: `Vehicle Double Parking`,
    [RequestType.AttemptedRape]: `Attempted Rape`,
    [RequestType.AttemptedSexualAssault]: `Attempted Sexual Assault`,
    [RequestType.Incest]: `Incest`,
    [RequestType.Rape]: `Rape`,
    [RequestType.RevengePorn]: `Revenge Porn`,
    [RequestType.SexualAssault]: `Sexual Assault`,
    [RequestType.SexualAssaultRapeNotByIntimatePartner]: `Sexual assault/rape (not by intimate partner)`,
    [RequestType.SexualHarassment]: `Sexual Harassment`,
    [RequestType.SexualHarmByPoliceOfficer]: `Sexual harm by police officer`,
    [RequestType.StatutoryRapeSexBetweenMinorAndAdult]: `Statutory rape (sex between minor and adult)`,
    [RequestType.HeardShooting]: `Heard Shooting`,
    [RequestType.SawShootingInCommunity]: `Saw Shooting in Community`,
    [RequestType.ShootingAtCallerDirectHomeCar]: `Shooting at caller (direct/home/car)`,
    [RequestType.ShootingAtNeighborDirectHomeCar]: `Shooting at neighbor (direct/home/car)`,
    [RequestType.IntoxicatedInBarClub]: `Intoxicated in bar/club`,
    [RequestType.IntoxicatedInVehicleNotDriving]: `Intoxicated in vehicle (not driving)`,
    [RequestType.IntoxicatedInsideBuilding]: `Intoxicated inside building`,
    [RequestType.IntoxicatedOnTheStreetSidewalk]: `Intoxicated on the street/sidewalk`,
    [RequestType.NeedlesDrugParaphernaliaOnGround]: `Needles/drug paraphernalia on ground`,
    [RequestType.SubstanceUseInPublic]: `Substance use in public`,
    [RequestType.YouthChildWithControlledSubstance]: `Youth/child with controlled substance`,
    [RequestType.AttemptedBurglaryRobbery]: `Attempted Burglary/Robbery`,
    [RequestType.Carjacking]: `Carjacking`,
    [RequestType.FraudGeneral]: `Fraud (general)`,
    [RequestType.HomeOfficeBurglarized]: `Home/Office burglarized`,
    [RequestType.Robbery]: `Robbery`,
    [RequestType.StolenVehicle]: `Stolen Vehicle`,
    [RequestType.TheftOfPersonalProperty]: `Theft of Personal Property`,
    [RequestType.VehicleBurglarized]: `Vehicle Burglarized`,
    [RequestType.AccessingAnAbortion]: `Accessing an abortion`,
    [RequestType.CallerRecievingPrankCalls]: `Caller Recieving Prank Calls`,
    [RequestType.ChronicCaller]: `Chronic Caller`,
    [RequestType.FindingCovidTesting]: `Finding Covid Testing`,
    [RequestType.FindingShelter]: `Finding Shelter`,
    [RequestType.FindingSTDSTITesting]: `Finding STD/STI Testing`,
    [RequestType.GeneralComplaints]: `General complaints`,
    [RequestType.HelpGettingFoodWater]: `Help getting food/water`,
    [RequestType.HelpGettingMedicine]: `Help getting medicine`,
    [RequestType.InfoAboutCommunityMeeting]: `Info about Community Meeting`,
    [RequestType.InfoAboutThisProgramCrisisTeam]: `Info about this program/crisis team`,
    [RequestType.NeedATow]: `Need a tow`,
    [RequestType.OtherFinancialMutualAid]: `Other financial/mutual aid`,
    [RequestType.Transport]: `Transport`,
    [RequestType.UtilitiesShutOff]: `Utilities shut off`,
    [RequestType.BrandishingWeapon]: `Brandishing weapon`,
    [RequestType.Gambling]: `Gambling`,
    [RequestType.NegativeActivityWhereChildrenArePresent]: `Negative activity where children are present`,
    [RequestType.PersonWithAGun]: `Person with a gun`,
    [RequestType.SellingDrugs]: `Selling drugs`,
    [RequestType.SexTrafficking]: `Sex Trafficking`,
    [RequestType.SexWork]: `Sex Work`,
    [RequestType.ThrowingObjectsSubstance]: `Throwing objects/substance`,
}
